---
- name: Razer Blade Ansible Playbook
  hosts: local
  become: true
  roles:
    - packages
    - preflight
    - ssh
    - zsh
    - alacritty
    - feh
    - picom
    - rofi
    - i3
    - tweaks
    - libinput
    - openrgb
    - vscode
    - nvidia
    - ollama
    - steam
    - pipewire
    - firefox
    - modules
    - telegram
    - devops
