---
- name: Basic Linux Setup
  hosts: local
  become: true
  roles:
    - preflight
    # - packages
    # - ssh
    # - zsh
    # - alacritty
    # - feh
    # - picom
    # - rofi
    - i3
    # - tweaks
    # - libinput
    # - openrgb
    # - vscode
    # - nvidia
    # - ollama
    # - steam
    # - pipewire
    # - firefox
    # - modules
    # - telegram
    # - devops
