---
- name: Install docker
  ansible.builtin.include_tasks: docker.yaml

- name: Install kubectl
  ansible.builtin.include_tasks: kubectl.yaml

- name: Install k9s
  ansible.builtin.include_tasks: k9s.yaml

- name: Install minikube
  ansible.builtin.include_tasks: minikube.yaml

- name: Install kubectx
  ansible.builtin.include_tasks: kubectx.yaml

- name: Install Lens
  ansible.builtin.include_tasks: lens.yaml
