all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    vm:
      hosts:
        qemu:
          ansible_connection: ssh
          ansible_port: 2222
          ansible_host: localhost
          ansible_user: user
