---
- name: Add i386 architecture support
  ansible.builtin.command:
    cmd: dpkg --add-architecture i386
  become: true
  changed_when: false

- name: Update package list
  ansible.builtin.package:
    update_cache: true
  become: true
  changed_when: false

- name: Install prerequisites
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
  become: true

- name: Download the Valve GPG key
  ansible.builtin.apt_key:
    url: http://repo.steampowered.com/steam/archive/stable/steam.gpg
    state: present
  become: true

- name: Add the Steam repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,i386] http://repo.steampowered.com/steam/ stable steam"
    state: present
    update_cache: true
  become: true

- name: Install 32-bit libraries for Steam
  ansible.builtin.apt:
    name:
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:i386
      - libc6:i386
      - libgl1:i386
      - libdrm2:i386
    state: present
  become: true

- name: Install the Steam client
  ansible.builtin.package:
    name:
      - steam-launcher
      - steam-devices
      - steam-libs
      - steam-libs-amd64
      - steam-libs-i386
    state: latest
  become: true
  changed_when: false

- name: Create Steam directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ logged_user }}"
    group: "{{ logged_user }}"
  loop:
    - "{{ logged_user_home }}/.steam/"
    - "{{ logged_user_home }}/.local/share/Steam/"
