---
- name: Download and install Ollama
  ansible.builtin.shell:
    cmd: "curl -fsSL https://ollama.com/install.sh | sh"
  args:
    creates: /usr/local/bin/ollama # Modify this path based on the actual binary location if needed
  become: true

- name: Verify Ollama installation
  ansible.builtin.command:
    cmd: "ollama --version"
  register: ollama_version
  changed_when: false

- name: Display Ollama version
  debug:
    msg: "Ollama version installed: {{ ollama_version.stdout }}"

- name: Download and install the latest Llama 3.2 model
  ansible.builtin.shell:
    cmd: "ollama pull llama:3.2"
  args:
    creates: /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/llama3.2/latest
  become: true

- name: Verify Llama 3.2 model installation
  ansible.builtin.command:
    cmd: "ollama list"
  register: ollama_models
  changed_when: false

- name: Display available models
  debug:
    msg: "Available models: {{ ollama_models.stdout }}"
