---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - xserver-xorg-input-libinput
      - xdotool
      - wmctrl
      - libinput-tools
    state: present
    update_cache: true

- name: Copy libinput touchpad configuration
  ansible.builtin.copy:
    src: 40-libinput.conf
    dest: /etc/X11/xorg.conf.d/40-libinput.conf
    mode: "0755"
    owner: "{{ logged_user }}"
    group: "{{ logged_user }}"

- name: Check if libinput-gestures is present
  ansible.builtin.stat:
    path: "/usr/bin/libinput-gestures"
  register: libinput_gestures_installed

- name: Clone libinput-gestures repository
  ansible.builtin.git:
    repo: "https://github.com/bulletmark/libinput-gestures.git"
    dest: /tmp/libinput-gestures
    version: master
  when: not libinput_gestures_installed.stat.exists

- name: Install libinput-gestures
  ansible.builtin.command: sudo make install
  args:
    chdir: /tmp/libinput-gestures
  when: not libinput_gestures_installed.stat.exists
  changed_when: false

- name: Add user to input group
  ansible.builtin.user:
    name: "{{ logged_user }}"
    groups: input
    append: true

- name: Copy libinput-gestures configuration file
  ansible.builtin.copy:
    src: libinput-gestures.conf
    dest: "{{ logged_user_home }}/.config/libinput-gestures.conf"
    owner: "{{ logged_user }}"
    group: "{{ logged_user }}"
    mode: "0755"

- name: Create libinput-gestures systemd service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Libinput Gestures Service
      After=graphical-session.target

      [Service]
      Type=simple
      ExecStart=/usr/bin/libinput-gestures
      Restart=on-failure
      User={{ logged_user }}
      Environment=DISPLAY=:1

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/libinput-gestures.service
    owner: root
    group: root
    mode: "0755"

- name: Reload systemd to recognize new service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable libinput-gestures service
  ansible.builtin.systemd:
    name: libinput-gestures
    enabled: true

- name: Start libinput-gestures service
  ansible.builtin.systemd:
    name: libinput-gestures
    state: started
