---
# Install dependencies for i3-gaps
- name: Install i3-gaps dependencies
  ansible.builtin.package:
    name:
      - i3lock
      - i3status
    state: present

# check i3 installation
- name: Check if i3 is present
  ansible.builtin.stat:
    path: "{{ logged_user_home }}/.i3-gaps"
  register: i3_gaps_dir

# Clone i3-gaps repository
- name: Clone i3-gaps repository
  ansible.builtin.git:
    repo: "https://github.com/Airblader/i3.git"
    dest: "{{ logged_user_home }}/.i3-gaps"
    version: "gaps-next"
  when: not i3_gaps_dir.stat.exists

# Build and install i3-gaps using Meson and Ninja
- name: Build and install i3-gaps
  ansible.builtin.shell: |
    cd "{{ logged_user_home }}/.i3-gaps"
    rm -rf build/
    meson build --prefix=/usr --sysconfdir=/etc
    ninja -C build
    sudo ninja -C build install
  args:
    executable: /bin/bash
    creates: /usr/bin/i3

# Create i3 config directory
- name: Create i3 config directory
  ansible.builtin.file:
    path: "{{ logged_user_home }}/.config/i3"
    state: directory
    mode: "0755"

# Copy i3 config file
- name: Copy i3 config file
  ansible.builtin.copy:
    src: config
    dest: "{{ logged_user_home }}/.config/i3/config"
    mode: "0644"
    owner: "{{ logged_user }}"
    group: "{{ logged_user }}"
