---
- name: Install Alacritty
  ansible.builtin.package:
    name: alacritty
    state: present

- name: Create Alacritty config directory
  ansible.builtin.file:
    path: "{{ logged_user_home }}/.config/alacritty"
    state: directory
    mode: '0755'

- name: Copy Alacritty configuration
  ansible.builtin.copy:
    src: alacritty.yml
    dest: "{{ logged_user_home }}/.config/alacritty/"
    mode: "0644"
